# Generated by Django 4.2.13 on 2024-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
