# Generated by Django 4.2.13 on 2024-06-02 13:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_options_place_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='content',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
