# Generated by Django 4.2.13 on 2024-06-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_content_alter_place_description_long'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PlaceImage',
        ),
    ]
