# Generated by Django 4.2.13 on 2024-06-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_placeimage_title_alter_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
