# Generated by Django 4.2.13 on 2024-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='places_plac_order_66e296_idx'),
        ),
    ]
